version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errorlint

    - bodyclose
    - nilerr
    - nilnil
    - durationcheck

    - misspell
    - unconvert
    - unparam
    - usestdlibvars

    - testifylint

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment

    errcheck:
      check-type-assertions: true
      check-blank: true

    testifylint:
      enable-all: true
      disable:
        - float-compare
        - go-require

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - funlen
          - gocognit
          - goconst

      - path: (^|/)(vendor|third_party|builtin|examples)(/|$)
        linters:
          - all

formatters:
  enable:
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - gomcrouter
